# Generated by Django 4.1.8 on 2023-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Lifestyle", "Lifestyle"),
                    ("Relationship", "Relationship"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=20,
            ),
        ),
    ]
